"""made models User, Appointment, Instructor, InstructorSchedule, Service, ServiceBooked, ServiceProvided initial design

Revision ID: 1b63367aa7ea
Revises: 
Create Date: 2023-03-06 19:38:12.708067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b63367aa7ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.Column('dates_available', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('price_expected', sa.Float(), nullable=True),
    sa.Column('price_full', sa.Float(), nullable=True),
    sa.Column('dicount', sa.Float(), nullable=True),
    sa.Column('cancellation', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('instructorschedule',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('service',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('serviceprovided',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.uid'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('services_booked',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.uid'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_booked')
    op.drop_table('serviceprovided')
    op.drop_table('service')
    op.drop_table('instructorschedule')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('instructor')
    # ### end Alembic commands ###
